from PyQt5 import QtCore, QtGui, QtWidgets
from WindowGUI2 import Ui_MainWindow
import sys, res

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 1391, 781))
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1371, 751))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(159, 40))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setStyleSheet("background-color: rgb(47, 47, 47);\n"
"")
        self.Home.setObjectName("Home")
        self.HomeLabel = QtWidgets.QLabel(self.Home)
        self.HomeLabel.setGeometry(QtCore.QRect(30, 30, 1311, 641))
        self.HomeLabel.setStyleSheet("color: white;\n"
"font-size: 100px;\n"
"")
        self.HomeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.HomeLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HomeLabel.setLineWidth(4)
        self.HomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HomeLabel.setObjectName("HomeLabel")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("home.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Home, icon, "")
        self.Camera = QtWidgets.QWidget()
        self.Camera.setStyleSheet("color: rgb(0, 0, 0);")
        self.Camera.setObjectName("Camera")
        self.widget_3 = QtWidgets.QWidget(self.Camera)
        self.widget_3.setGeometry(QtCore.QRect(30, 20, 1311, 651))
        self.widget_3.setObjectName("widget_3")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(520, 90, 781, 531))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 100px;")
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_8.setLineWidth(4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 20, 93, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 20, 93, 28))
        self.pushButton_5.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 261, 31))
        self.comboBox.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 491, 311))
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_9.setLineWidth(4)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(10, 410, 491, 211))
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_10.setLineWidth(4)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("camera.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Camera, icon1, "")
        self.Gallery = QtWidgets.QWidget()
        self.Gallery.setObjectName("Gallery")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gallery.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Gallery, icon2, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Settings)
        self.tabWidget_2.setGeometry(QtCore.QRect(330, 100, 681, 481))
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(50, 220, 451, 41))
        self.textEdit.setStyleSheet("background-color: rgb(248, 255, 242);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 220, 121, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(249, 246, 255);\n"
"border-solid: 7px;\n"
"border-color: rgb(50,50, 50);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(295, 360, 93, 28))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 141, 41))
        self.label_3.setStyleSheet("color: white;\n"
"font-size: 20px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(295, 360, 93, 28))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(290, 100, 311, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 160, 311, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 220, 311, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 280, 311, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(81, 100, 151, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(79, 160, 151, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(81, 220, 151, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(80, 280, 151, 31))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px;")
        self.label_7.setObjectName("label_7")
        self.tabWidget_2.addTab(self.tab_2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("settings.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Settings, icon3, "")
        self.Help = QtWidgets.QWidget()
        self.Help.setObjectName("Help")
        self.label_2 = QtWidgets.QLabel(self.Help)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 1291, 601))
        self.label_2.setStyleSheet("color: white\n"
"")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(4)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("help.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Help, icon4, "")
        self.Exit = QtWidgets.QWidget()
        self.Exit.setObjectName("Exit")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("exit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Exit, icon5, "")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(1160, 12, 220, 48))
        self.pushButton.setStyleSheet("background-color: rgb(243, 243, 243);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("exit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon6)
        self.pushButton.setIconSize(QtCore.QSize(200, 40))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HomeLabel.setText(_translate("MainWindow", "Camera Feed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Home"))
        self.label_8.setText(_translate("MainWindow", "Camera Feed"))
        self.pushButton_4.setText(_translate("MainWindow", "Start"))
        self.pushButton_5.setText(_translate("MainWindow", "Stop"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Select Camera"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select Camera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Camera), _translate("MainWindow", "Camera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gallery), _translate("MainWindow", "Gallery"))
        self.pushButton_2.setText(_translate("MainWindow", "Browse"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "File Location"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "File "))
        self.pushButton_6.setText(_translate("MainWindow", "Save"))
        self.label_4.setText(_translate("MainWindow", "Old Username  :"))
        self.label_5.setText(_translate("MainWindow", "New Username :"))
        self.label_6.setText(_translate("MainWindow", "Old Password   :"))
        self.label_7.setText(_translate("MainWindow", "New Password  :"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Security"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings"))
        self.label_2.setText(_translate("MainWindow", "Video Tutorial"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Help), _translate("MainWindow", "Help"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Exit), _translate("MainWindow", "Exit"))
        self.pushButton.setText(_translate("MainWindow", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
